name: Visit website using Chrome
on:
  workflow_dispatch:
    inputs:
      url:
        description: "Enter the URL of the website to visit"
        required: true
jobs:
  visit-website:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3]
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip google-chrome-stable xvfb tzdata
        pip3 install fake_useragent
    - name: Randomize time zone
      run: |
        sudo sh -c 'echo $(tzselect) > /etc/timezone'
        sudo dpkg-reconfigure -f noninteractive tzdata
    - name: Use Chrome to visit website
      env:
        DISPLAY: :99.0
      run: |
        user_agent=$(python3 -c 'from fake_useragent import UserAgent; print(UserAgent().random)')
        echo "User Agent: ${user_agent}"
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        google-chrome --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 --user-agent="${user_agent}" --disable-dev-shm-usage ${{ inputs.url }}
        sleep $(shuf -n 1 -e "5m" "10m" "15m" "20m" "25m" "30m" "35m" "40m" "45m" "50m" "55m" "60m")
        pkill chrome
